- server/db/models/product.js
- server/db/models/user.js
> Created Product Model

- server/db/models/orderproduct.js
> basic OrderProduct model

- package-lock.json
- package.json
- script/seed.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/orderproduct.js
> synced database

- script/seed.js
- server/db/models/cartProduct.js
- server/db/models/index.js
- server/db/models/order.js
- server/index.js
> Updated All Models

- server/api/cartProducts.js
- server/api/orders.js
- server/api/users.js
- server/db/models/index.js
- server/index.js
> fixed routes and models

- client/components/AllProducts.js
- client/routes.js
- client/store/reducers/productsReducer.js
> all products component

- client/components/navbar.js
- public/style.css
> Added links, search box to nav bar

- client/components/AllProducts.js
- client/components/ProductThumb.js
- client/components/singleProduct.js
- client/store/reducers/allProducts.js
> product thumb imgPath bug fixed

- client/components/CartList.js
- client/components/CartProduct.js
- client/routes.js
- client/store/reducers/orderProducts.js
- script/seed.js
- server/api/orderProduct.js
- server/db/models/index.js
- server/db/models/orderproduct.js
- server/index.js
> added cart redux and react

- script/seed.js
- server/db/models/product.js
- server/db/models/product.spec.js
> added first test

- client/components/CartProduct.js
- client/components/CartProduct.spec.js
- client/components/OrderHistoryItem.js
- client/components/OrderHistoryItem.spec.js
- client/components/ProductThumb.js
- client/components/ProductThumb.spec.js
- server/api/orderProduct.spec.js
- server/api/orders.spec.js
- server/api/products.spec.js
- server/db/models/order.spec.js
- server/db/models/orderproduct.spec.js
> Basic tests

- client/components/AllProducts.js
- client/components/CartList.js
- client/components/CartProduct.js
- client/components/CheckoutPage.js
- client/components/OrderHistory.js
- client/components/OrderHistoryItem.js
- client/components/ProductThumb.js
- client/components/singleProduct.js
- client/routes.js
- client/store/reducers/orderProducts.js
- client/store/reducers/orders.js
- public/style.css
- server/api/orderProduct.js
- server/api/orders.js
- server/api/products.js
- server/db/models/product.js
- server/db/models/product.spec.js
> Css update

- client/components/CartList.js
- client/components/CartProduct.js
- client/store/reducers/orderProducts.js
- server/api/orderProduct.js
- server/api/orders.js
- server/db/models/orderproduct.js
> added cart editing

- client/store/reducers/orderProducts.js
- server/api/orderProduct.js
- server/api/orders.js
> fixed cart page bug

- client/components/AllProducts.js
- client/components/CartList.js
- client/components/CartProduct.js
- client/components/CheckoutPage.js
- client/components/OrderHistoryDetails.js
- client/components/OrderHistoryItem.js
- client/components/singleProduct.js
- client/store/index.js
- client/store/reducers/cartProducts.js
- client/store/reducers/orderProducts.js
- client/store/reducers/orders.js
- public/style.css
- server/api/orderProduct.js
- server/api/orders.js
- server/db/models/orderproduct.js
- server/db/models/product.js
> Add historic cost

- client/components/AccountPage.js
- client/components/CartList.js
- client/components/CartProduct.js
- client/components/CheckoutPage.js
- client/components/OrderHistory.js
- client/components/OrderHistoryDetails.js
- client/components/OrderHistoryItem.js
- client/components/ProductThumb.js
- public/style.css
- server/api/orders.js
- server/db/models/product.js
- webpack.config.js
> updated css theme for site

- client/components/AccountPage.js
- client/store/reducers/user.js
- public/style.css
- server/api/users.js
> user profile now editable

- client/components/HomePage.js
- client/components/auth-form.js
- public/style.css
> redirect upon checkout to orderConfirmation

- client/components/CartList.js
- client/components/CartProduct.js
- client/components/Navbar.js
- client/store/reducers/guestCartProducts.js
> can delete guest cart product

- client/components/tests/CartProduct.spec.js
> update CartProduct component test spec with additional props

- client/components/CartList.js
- client/components/CartProduct.js
- client/components/Navbar.js
- client/components/tests/CartProduct.spec.js
- client/store/reducers/guestCartProducts.js
Reverts Donuts-Org/donuts-grace-shopper#50
> Revert "login bug fixed"

- client/components/CartList.js
- client/components/auth-form.js
> Guest checkout from cart list

- client/components/AllProducts.js
- client/components/CartList.js
- client/components/CartProduct.js
- client/components/singleProduct.js
- client/store/reducers/cartProducts.js
- client/store/reducers/guestCartProducts.js
> guest cart update working

- client/components/AccountPage.js
- client/components/auth-form.js
- client/store/reducers/allProducts.spec.js
- server/auth/index.js
- server/db/models/user.js
> Fixed account edit React Form and added a few validations

- client/components/AccountPage.js
- client/components/AllProducts.js
- client/components/CartList.js
- client/store/reducers/cartProducts.js
- server/api/orderProduct.js
- server/api/orders.js
- server/api/users.js
- server/auth/index.js
- server/db/models/user.js
> fixed add to cart bug, added more route security

- client/components/CheckoutPage.js
- client/components/Navbar.js
- client/routes.js
- client/store/reducers/guestCartProducts.js
- client/store/reducers/orders.js
- public/style.css
- server/api/orderProduct.js
- server/api/orders.js
- server/api/users.js
> fixed bugs for guest checkout

- server/api/users.spec.js
- server/db/models/user.spec.js
Reverts Donuts-Org/donuts-grace-shopper#58
> Revert "update user model and route specs to follow updated user model valida…"

- client/components/AccountPage.js
- client/components/CartList.js
- client/components/CartProduct.js
- client/components/CheckoutPage.js
- client/components/singleProduct.js
- client/store/reducers/orders.js
- server/api/users.js
> removed debugging console logs
